### ISSUE TITLE
AppleTV 1st - 3rd Gen

### ISSUE THREAD

**Issue by chikkevin** [9magnets/HopePoint#1]
Is there a way to make this tool compatible with older version of TVOS, currently I am running 7.2.1 on the 3rd generation of Apple TV. It would be awesome if we could run this tool on Apple TV's running OS as low as 4.1.

**Comment by CameronBanga** [comment]
@chikkevin Going to have to close this one, currently not possible. :-/ 

Requires the tvOS 9+ SDK, so that we can load UI kit apps on it. Something _may_ be possible if you could jailbreak/sideload apps onto the old Apple TV, but I wouldn't have any idea on that. And I'm not sure anything on the old tv is really anything other than the tv xml apps, so I'm not sure the APIs are even there to do such a thing. 

But yeah, won't be possible with Hope Point, sorry!

**Comment by CameronBanga** [comment]
@chikkevin If you're looking to test old Apple TVs, let me know your use case, I may have a few ideas on how you could go about doing that. Ping me via email at cbanga@9magnets.com.
